stages:
  - test

maven_test:
  stage: test
  image: maven
  tags:
    - docker
  script:
    - mvn verify
    - mvn package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/dashboard?id=maven_archetype_simple
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml