stages:
  - test

maven_test:
  stage: test
  image: maven
  tags:
    - docker
  script:
    - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml